name: Copyright Check

permissions:
  contents: write

on:
  pull_request:
    paths:
      - 'src/**'
      - 'examples/**'
  push:
    paths:
      - 'src/**'
      - 'examples/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging SHA and Branch
        run: |
          echo "Current SHA: $GITHUB_SHA"
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Recent commits:"
          git log --oneline -n 10

      - name: Check for changes
        run: |
          git fetch origin master
          echo "Commits in master:"
          git log origin/master --oneline
          echo "Commits in SHA:"
          git log $GITHUB_SHA --oneline

      - name: Debug GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh auth login
          gh auth status
          gh config list

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Download copyright check script
        run: |
          curl -O https://raw.githubusercontent.com/Tinyu-Zhao/check-copyright/master/check_copyright.py

      - name: Download setup script
        run: |
          curl -O https://raw.githubusercontent.com/Tinyu-Zhao/check-copyright/master/setup.py

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --user setuptools
          PYTHONUSERBASE=$HOME/.local python3 setup.py install --user

      - name: Check all files
        run: |
          # List all files in the specified directories with specific extensions
          files=$(find src examples \( -name "*.ino" -o -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" \) | tr '\n' ' ')
          echo "Files to check: $files"
          if [ -n "$files" ]; then
            PYTHONPATH="${HOME}/.local/lib/python3.*/site-packages" python3 check_copyright.py $files
          else
            echo "No files found to check."
          fi

      - name: Commit changes if any
        id: commit_changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
            echo "status=unchanged" >> $GITHUB_ENV
          else
            echo "Changes detected, creating a new branch and PR..."
            
            # Create a new branch
            git checkout -b copyright-update-${{ github.run_id }}
            
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Add copyright notices"
            
            # Push to the new branch
            git push --set-upstream origin copyright-update-${{ github.run_id }}
            
            # Create a pull request using GitHub CLI
            gh pr create --title "Add copyright notices" --body "This PR includes copyright notices for updated files." --base master --head copyright-update-${{ github.run_id }}
            
            echo "status=modified" >> $GITHUB_ENV
          fi
